@hostAddr = http://localhost:5079

@nurseryId = 1

###

# Task 1

GET {{hostAddr}}/api/Nurseries/{{nurseryId}}/batches/
Accept: application/json

###


# Task 2

POST {{hostAddr}}/api/Batches
Content-Type: application/json

{
  "quantity": 700,
  "species": "Some Species",
  "nursery": "Some Nursery",
  "responsible": [
    {
      "employeeId": 5,
      "role": "Supervisor"
    },
    {
      "employeeId": 3,
      "role": "Planter"
    }
  ]
}

###

